version: "3.8"

services:
  #  api:
  #    build: .
  #    ports:
  #      - "3000:3000"
  #    environment:
  #      - DATABASE_URL=postgresql://user:password@db:5432/dbname
  #      - REDIS_URL=redis://valkey:6379
  #    depends_on:
  #      - db
  #      - valkey
  #      - ./app:/app/app
  #
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - searxng_settings:/AskOwl/data/searxng/
    networks:
      - AskOwl-Net

  searXNG:
    image: searxng:latest
    environment:
      - BASE_URL=http://search:8080
    ports:
      - 8080:8080
    volumes:
      - searxng_settings:/etc/searxng/:Z
    networks:
      - AskOwl-Net

#  valkey:
#    image: valkey/valkey:7-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - valkey_data:/data
networks:
  AskOwl-Net:
    external: false

volumes:
  postgres_data:
  searxng_settings:
#  valkey_data:
