[project]
name = "askowlapi"
version = "0.1.0"
description = "AskOwl backend API."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.3",
    "fastapi-users[sqlalchemy]>=15.0.1",
    "uvicorn[standard]>=0.38.0",
]
